# Generated by Django 5.2.6 on 2025-09-25 01:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('organization', 'Organization')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('counseling_center', 'Counseling Center'), ('mental_health_center', 'Mental Health Center'), ('ngo', 'Non-Governmental Organization'), ('government_agency', 'Government Agency'), ('private_practice', 'Private Practice'), ('other', 'Other')], max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Philippines', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('services_offered', models.TextField(blank=True)),
                ('operating_hours', models.TextField(blank=True)),
                ('emergency_services', models.BooleanField(default=False)),
                ('insurance_accepted', models.TextField(blank=True)),
                ('languages_spoken', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_documents', models.FileField(blank=True, null=True, upload_to='organization_docs/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('counselor', 'Counselor'), ('psychologist', 'Psychologist'), ('psychiatrist', 'Psychiatrist'), ('social_worker', 'Social Worker'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
