# Generated by Django 5.2.6 on 2025-09-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role_organization_organizationstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
