# Generated by Django 5.2.6 on 2025-09-16 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('clinical_psychologist', 'Clinical Psychologist'), ('psychiatrist', 'Psychiatrist'), ('counselor', 'Counselor'), ('therapist', 'Therapist'), ('social_worker', 'Social Worker'), ('peer_support', 'Peer Support Specialist')], max_length=30)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('languages', models.CharField(default='English, Filipino', max_length=200)),
                ('available_days', models.CharField(blank=True, max_length=100)),
                ('available_hours', models.CharField(blank=True, max_length=100)),
                ('is_telehealth', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
            },
        ),
        migrations.CreateModel(
            name='SelfHelpExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('breathing', 'Breathing Exercise'), ('meditation', 'Meditation'), ('journaling', 'Journaling'), ('grounding', 'Grounding Technique'), ('progressive_relaxation', 'Progressive Muscle Relaxation'), ('mindfulness', 'Mindfulness'), ('cognitive', 'Cognitive Exercise')], max_length=30)),
                ('instructions', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('audio_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('exercise', 'Exercise'), ('meditation', 'Meditation'), ('contact', 'Professional Contact'), ('hotline', 'Crisis Hotline'), ('app', 'Mobile App'), ('book', 'Book/Publication')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_free', models.BooleanField(default=True)),
                ('is_24_7', models.BooleanField(default=False)),
                ('languages_supported', models.CharField(default='English, Filipino', max_length=200)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalhealth.resourcecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResourceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('viewed', 'Viewed'), ('bookmarked', 'Bookmarked'), ('rated', 'Rated'), ('shared', 'Shared'), ('contacted', 'Contacted')], max_length=20)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentalhealth.professionalcontact')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentalhealth.mentalhealthresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
